---
- name: onyx_clean_config
  hosts: your_switches
  gather_facts: no
  connection: network_cli
  become: yes
  become_method: enable
  vars:
    ansible_network_os: onyx
  roles:
      - { role: onyx_clean_config, tags: ['clean_config']}
